### ISSUE TITLE
Week 1 Individual Project Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [bvue/MyProject#1]
Hi Bao,

Looks like it's time to get rolling:
- [ ] document your problem statement
- [ ] create a project plan, week by week
- [ ] add your weekly journal entries (we are almost on week 3 already!)
- [ ] add your time log (time spent on the project and time spent on activities/exercises/readings)
- [ ] screen design should be well underway, if not complete, before Week 3 class

Let me know if you have any questions and be sure to check out my individual project (Fat Bike Trail Reports), if you need any examples to get you started on the items I mentioned above.

**Comment by bvue** [comment]
Yep, got it all updated!
